# Data Structure

- Its way of storing values in system in efficient manner.

# Basic Data Structures / Data Types

1. Integer
2. Float
3. Boolean
4. String

In [2]:
type(100)

int

In [3]:
type(100.0)

float

In [4]:
type(True)

bool

In [2]:
type('Yellow')

str

# Variable
- Container that hold certain information.
- Reserved memory location to store any data types
- Syntax:

    `<variable_name>` = `<assigned_value>`

In [6]:
a = 10
print(a)

10


# Operators

1. Arithmetic Operator
2. Boolean Operator
3. Special Operator
4. Conditional Operator
5. Memebership Operator

## 1. Aritmetic Operators

1. Addition
2. Substraction
3. Multiplication
4. Division
5. Modular Division
6. Exponential 
7. Modulus

In [4]:
a = 10
b = 20

In [6]:
a + b

30

In [10]:
a - b

-10

In [11]:
a * b

200

In [12]:
a / b

0.5

In [13]:
a % b

10

In [14]:
a ** b

100000000000000000000

In [8]:
a // b

0

## 2. Conditional Operators

1. Greater than
2. Greater than equal to
3. Less than
4. Less than equal to
5. Equal to
6. Not equal to

In [16]:
10 > 5

True

In [17]:
10 >= 5

True

In [18]:
10 < 5

False

In [19]:
10 <= 5

False

In [20]:
10 == 5

False

In [21]:
10 != 5

True

## 3. Boolean Operators

1. AND Gate
2. OR Gate
3. NOT

In [22]:
True and True

True

In [23]:
True and False

False

In [24]:
10 > 5 and 5 > 10

False

In [25]:
True or False

True

In [26]:
True or True

True

In [27]:
10 > 5 or 5 > 10

True

In [28]:
not True

False

## 4. Special Operators

1. is
2. is not

- The Equality operator (==) compares the values of both the operands and checks for value equality. Whereas the ‘is’ operator checks whether both the operands refer to the same object or not (present in the same memory location).

In [29]:
(5 == 5) is True

True

In [30]:
(5 == 10) is not True

True

- Over here, `is` is the special operator, where as not is the boolean operator combined with special operator.

## 5. Membership Operators

1. in
2. not in

In [31]:
'h' in 'hello'

True

In [32]:
5 in [1, 2, 3, 4, 5]

True

In [36]:
'a' not in 'Hamid'

False

- Over here, mind it. Python is **case sensitive.**

# Input

- input from user/ take value from keyboard or user.
- input ( ) : This function first takes the input from the user and convert it into string. Type of the returned object always will be <type ‘str’>. It does not evaluate the expression it just return the complete statement as String.

In [39]:
a  = input()

10000


In [40]:
type(a)

str

# Type Casting
- method of converting one data type to another
1. int()
2. str()
3. float()

In [43]:
a = input()

100


In [44]:
float(a)

100.0

In [46]:
a = 7
print(type(a))

<class 'int'>


## Implicit Type Conversion
- In this,  methods, Python converts data type into another data type automatically. In this process, users don’t have to involve in this process. 

In [47]:
a = 7
print(type(a))
b = 3.0
print(type(b))
c = a + b
print(c)
print(type(c))
d = a * b
print(d)
print(type(d))

<class 'int'>
<class 'float'>
10.0
<class 'float'>
21.0
<class 'float'>


## Explicit Type Casting
- In this method, Python need user involvement to convert the variable data type into certain data type in order to the operation required.

In [48]:
a = input()

10


In [49]:
ab = str(a)
print(ab)
type(ab)

10


str

In [50]:
ac = float(a)
print(ac)
type(ac)

10.0


float

In [51]:
ad = int(a)
print(ad)
type(ad)

10


int

# Exercises

## Senario 1 
- I want give hike of 5% to amit_salary = "5000". Perform operation

In [53]:
hike = 5 / 100
amit_salary = '5000'
amit_salary = int(amit_salary)
hiked_salary = amit_salary * hike
hiked_salary

250.0

## Senario 2
- Can python convert str to int / float?

In [54]:
string = 'hamid'
convert = float(string)

ValueError: could not convert string to float: 'hamid'

- Python cannot convert string into float or int.

# 3. Write a program to swap two numbers.

- input: a = 10, b = 20

- Expected output: a = 20, b = 10

In [58]:
a = 10
b = 20
temp = 0
temp = a
a = b
b = temp
a, b

(20, 10)

In [59]:
a, b = 10, 20
a, b = b, a
a, b

(20, 10)

# Conditional Statement
1. if statement / if-else
    syntax:
        'if condition:
            statment1
            staement2
         else:
            statement3
            statement4
3. elif statement(More than two conditions)
    syntax:
        if condition1:
            statement1
        elif condition2:
            statement2
        else:
            statement3

In [60]:
a = 10
b = 100
# condition is a < b, what if we have more than one condition
if a < b:
    print('True')
else:
    print('Tera baap aaya tha yaha pe')

True


In [61]:
# we have more than one condition to check.
if a < b:
    print('a is less than b')
elif a > b:
    print('b is greater than a')
else:
    print('both are equal')

a is less than b


# Nesting if statements

In [62]:
marks = float(input())
if marks > 0 and marks < 100:
    if marks >= 90:
        print('grade A')
    elif marks >= 80:
        print('grade B')
    elif marks >= 70:
        print('grade C')
    elif marks >= 60:
        print('grade D')
    elif marks < 60:
        print('grade F')
else:
    print('Bad Score')

78
grade C


# Advanced Data Structures

## 1. List

- features:
1. Mutable
2. Representation using []
3. Ordered
4. Duplicated

syntax:

`<list_name>` = `[value1, value2, ...]`

In [110]:
# 1.List with same data type
salary = [1000, 2000, 1500, 2300, 4000]
print(salary)
salary

[1000, 2000, 1500, 2300, 4000]


[1000, 2000, 1500, 2300, 4000]

In [74]:
# 2.List with different data types
salaries = ['Sunita', 1000, 'tina', 2000, 'Hina',1500, 'Renna', 2330, 'Ronak', 2345]
print(salaries)
salaries

['Sunita', 1000, 'tina', 2000, 'Hina', 1500, 'Renna', 2330, 'Ronak', 2345]


['Sunita', 1000, 'tina', 2000, 'Hina', 1500, 'Renna', 2330, 'Ronak', 2345]

# List within a list, Nested List

In [72]:
income3 = [['Sunita', 1000],
['Tina', 2000],
['Hina', 15000.5],
['Reena', 456678],
['Ronak',1234]]
print(income3)
income3

[['Sunita', 1000], ['Tina', 2000], ['Hina', 15000.5], ['Reena', 456678], ['Ronak', 1234]]


[['Sunita', 1000],
 ['Tina', 2000],
 ['Hina', 15000.5],
 ['Reena', 456678],
 ['Ronak', 1234]]

## 1.2 Indexing in List
- In order to access particular element from a list we use indexing.
- Elements are refered as numbering starts from 0 and end at any number.

In [75]:
# +ve indexing
# -ve indexing
salaries[3]

2000

In [76]:
salaries[-2]

'Ronak'

## 1.3 List Slicing
- fetching a subset of element/s from a list using indexing concept

In [77]:
# Fetch salaries from Hina to Ronak
salaries[4:10]

['Hina', 1500, 'Renna', 2330, 'Ronak', 2345]

### Accessing and slicing elements from whole/ within list.

In [78]:
# hina's salary from income3
income3[2][1]

15000.5

In [82]:
income3[2:4][1:2]

[['Reena', 456678]]

In [83]:
income3[2:4][1]

['Reena', 456678]

### 1. Chaniging List elements

In [84]:
salaries

['Sunita', 1000, 'tina', 2000, 'Hina', 1500, 'Renna', 2330, 'Ronak', 2345]

In [85]:
salaries[1] = 200

In [86]:
salaries

['Sunita', 200, 'tina', 2000, 'Hina', 1500, 'Renna', 2330, 'Ronak', 2345]

### 2. Adding elements to list

In [89]:
salaries_new = salaries + ['Amit', 1100]
print(salaries_new)
salaries_new

['Sunita', 200, 'tina', 2000, 'Hina', 1500, 'Renna', 2330, 'Ronak', 2345, 'Amit', 1100]


['Sunita',
 200,
 'tina',
 2000,
 'Hina',
 1500,
 'Renna',
 2330,
 'Ronak',
 2345,
 'Amit',
 1100]

In [92]:
list1=[1,2,3,4,5]
list2=[4,5,6,7,8,89]
list3 = list1 + list2
list3

[1, 2, 3, 4, 5, 4, 5, 6, 7, 8, 89]

### 3. Deleting element or list. 

In [91]:
del(salaries_new[-2:-1])
salaries_new

['Sunita', 200, 'tina', 2000, 'Hina', 1500, 'Renna', 2330, 'Ronak', 2345, 1100]

# Related functions in list

In [93]:
len(income3)

5

In [94]:
sorted(list3, reverse=True)

[89, 8, 7, 6, 5, 5, 4, 4, 3, 2, 1]

# List Methods

In [96]:
list1.append(list2)
list1

[1, 2, 3, 4, 5, [4, 5, 6, 7, 8, 89]]

In [97]:
# Insert
cities = ['Bangalore', 'Hyderabad', 'Delhi']
cities.insert(1,'Chennai')
cities

['Bangalore', 'Chennai', 'Hyderabad', 'Delhi']

In [98]:
# Count
count = cities.count('Bangalore')
count

1

In [101]:
# To remove elements from the list, we have pop()
cities
cities.pop(1)

'Chennai'

In [102]:
name = 'Amit'
name.replace('t','thhhhhh')

'Amithhhhhh'

# Tuple
- Tuple similar to list but only difference is that it is immutabe(cannot change values in tuple
- We repsent by ()
- Tuple can have any data type

In [104]:
# Creating a tuple
tup = (1, 2, 3)
tup

(1, 2, 3)

In [105]:
type(tup)

tuple

In [106]:
print(type(tup))

<class 'tuple'>


In [107]:
# Exceptional Case
tup1 = ('hella')
type(tup1)

str

In [108]:
tup2 = ('hella',)
type(tup2)

tuple

In [111]:
tup4 = ('hella', 1, 2, 3, True)
tup4

('hella', 1, 2, 3, True)

In [112]:
# Indexing
tup4[3], tup4[2]

(3, 2)

In [113]:
# In tuple +ve & -ve indexing works
tup4[-1] 

True

In [114]:
# Tuple immutable examples:
tup4[2] = 2.43

TypeError: 'tuple' object does not support item assignment

In [115]:
# Tuple Methods
t = (1, 1, 1.1, 2, 'hello', 'hello')
t.count('hello')

2

In [116]:
t.count(1)

2

In [117]:
t.index(1)

0

In [118]:
# Slicing 
# : is slicing operator
tup4[1:3]

(1, 2)

In [121]:
tup4[-2:]

(3, True)

In [122]:
tup4[:-1]

('hella', 1, 2, 3)

In [123]:
tup + tup4

(1, 2, 3, 'hella', 1, 2, 3, True)

In [124]:
# Inside the tuple, list is immutabe.
t3 = (1, 2, 4, [1, 2, 3], 11, 10)
t3

(1, 2, 4, [1, 2, 3], 11, 10)

In [126]:
# Alterning element in list inside the tuple
t3[3][0] = 10
t3

(1, 2, 4, [10, 2, 3], 11, 10)

In [127]:
# Inside the list, tuple are immutable.
l1 = [1, 2, 3, (1, 2), 10]
l1

[1, 2, 3, (1, 2), 10]

In [128]:
l1[3][0] = 12

TypeError: 'tuple' object does not support item assignment

# Set

- Set is unordered, with unique values(no duplicates) and it is immutable.
- We represent using `set()`, `{}`
- Cannot perform 
    1. Slicing
    2. Indexing
    3. Special Operators, like `+` and `*`

In [129]:
s1 = {1, 2, 3}
s1

{1, 2, 3}

In [130]:
type(s1)

set

In [131]:
s = {}
s

{}

In [132]:
type(s)

dict

In [11]:
s2 = {1, 2, 3, 10, 112,12}
s2

{1, 2, 3, 10, 12, 112}

In [12]:
type(s2)

set

In [134]:
# Indexing is not allowed
s2[2]

TypeError: 'set' object is not subscriptable

In [135]:
# Slicing is not allowed
s2[0:2]

TypeError: 'set' object is not subscriptable

In [136]:
s4 ={1, 2, 3, 4, (10, 111, 100)}
s4

{(10, 111, 100), 1, 2, 3, 4}

In [138]:
# set method 1
s4.union(s1)

{(10, 111, 100), 1, 2, 3, 4}

In [139]:
# set method 2
s4.intersection(s1)

{1, 2, 3}

In [140]:
# set method 3
s4.pop()

1

In [141]:
s4

{(10, 111, 100), 2, 3, 4}

In [142]:
# empty set cannot removes an element.
s.pop()

TypeError: pop expected at least 1 argument, got 0

In [143]:
# Does not take any parameters
s4.pop(1)

TypeError: pop() takes no arguments (1 given)

In [144]:
# # set method 4
s4.remove(3)
s4

{(10, 111, 100), 2, 4}

In [145]:
# Special operatiion aren't allowed
s2 + s6

NameError: name 's6' is not defined

# Dictionaries

- Unordered collection of elements
- syntax:
    `{key1 : value1, key2 : value2, . . .}`
- Data in dictionaries are stores in the form of keys and values.
- KEYS:
    - As indexing is not possible in dictionaries here we can use keys as index to access elements value.
    - Keys must be unique.
    - Keys can be immutable data type(string, int, float).
- Represented using {}
- Note: Dictionary is mutable but not its keys

In [146]:
d  = {1:'hello', 2:'jigsaw', 3:'maniapl', 4:'unext'}
d

{1: 'hello', 2: 'jigsaw', 3: 'maniapl', 4: 'unext'}

In [147]:
type(d)

dict

In [148]:
d1 = {"A":'One', "B":'Two', 'C':'Three'}
d1

{'A': 'One', 'B': 'Two', 'C': 'Three'}

In [149]:
d[1]

'hello'

In [150]:
d1['A']

'One'

In [151]:
# You can add a key, by indexing the dictionary variable.
d[5] = 'Bombay'
d

{1: 'hello', 2: 'jigsaw', 3: 'maniapl', 4: 'unext', 5: 'Bombay'}

In [152]:
# You can change the values of dictionary by indexing 
# the dictionary variable
d[1]= 'hi'
d

{1: 'hi', 2: 'jigsaw', 3: 'maniapl', 4: 'unext', 5: 'Bombay'}

In [153]:
# Methods of Dictionaries
d.keys()

dict_keys([1, 2, 3, 4, 5])

In [154]:
d.values()

dict_values(['hi', 'jigsaw', 'maniapl', 'unext', 'Bombay'])

In [155]:
d.items()

dict_items([(1, 'hi'), (2, 'jigsaw'), (3, 'maniapl'), (4, 'unext'), (5, 'Bombay')])

In [156]:
# We can only approach the keys in 
# dictionaries not the values.
'A' in d1

True

In [157]:
# for values we go for dict.values()
'maniapl' in d.values()

True

In [158]:
d.get(4)

'unext'

In [159]:
d.pop(1)

'hi'

In [160]:
d.clear()

In [161]:
d

{}

In [162]:
# This eradicate the dictionary
del d1

In [164]:
d1 = {0:'Hello', 1:'Hiii'}
d2 = {1: 'hi', 2: 'jigsaw', 3: 'maniapl', 4: 'unext', 5: 'Bombay'}
d1.update(d2)

In [165]:
d1

{0: 'Hello', 1: 'hi', 2: 'jigsaw', 3: 'maniapl', 4: 'unext', 5: 'Bombay'}

In [166]:
# Nested Dictionaries:
d2 ={'1':{'Name': "John", 'age': 29, 'gender': 'Male'},
     '2':{'Name': "Marie", 'age': 39, 'gender': 'female'}}
d2

{'1': {'Name': 'John', 'age': 29, 'gender': 'Male'},
 '2': {'Name': 'Marie', 'age': 39, 'gender': 'female'}}

In [167]:
d2.get('1')

{'Name': 'John', 'age': 29, 'gender': 'Male'}

In [168]:
d2.get('1').get('Name')

'John'

# Strings

In [169]:
s = "python"

In [170]:
# 1
s.capitalize()

'Python'

In [171]:
# 2
s.upper()

'PYTHON'

In [172]:
# 2
s.lower()

'python'

In [173]:
# 4
s_2 = "the discovery of india"
s_2

'the discovery of india'

In [174]:
s_2.capitalize()

'The discovery of india'

In [175]:
s_2.title()

'The Discovery Of India'

In [176]:
s_2.find('dis')

4

In [177]:
s_2.find('of')

14

In [178]:
s_2.count('i')

3

In [179]:
s_2.startswith('t')

True

In [180]:
s_2.endswith('p')

False

In [181]:
numstr = "lenovo L490"

In [183]:
numstr.isalpha()

False

In [184]:
numstr.isalnum()

False

In [185]:
numstr = "lenovoL490"

In [186]:
numstr.isalnum()

True

In [187]:
numstr.isdigit()

False

In [188]:
' india the discovery of india '.strip()

'india the discovery of india'

In [189]:
'india the discovery of india'.strip('in')

'dia the discovery of india'

In [190]:
'india the discovery of indiain'.strip('in')

'dia the discovery of india'

In [191]:
'india the discovery of indiain'.rstrip('in')

'india the discovery of india'

In [192]:
'india the discovery of indiain'.lstrip('in')

'dia the discovery of indiain'

In [193]:
# Split Method
data = 'From stephen.macfee@ust.ac.za Sat Jun 5 09:14:16 2008'

In [194]:
data.split()

['From', 'stephen.macfee@ust.ac.za', 'Sat', 'Jun', '5', '09:14:16', '2008']

# Range Function

syntax:

`range(start, stop, step)`

In [195]:
list(range(1, 10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

## Scenario 1
- Print list of even numbers

In [200]:
print(list(range(2, 100, 2)))

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98]


In [201]:
list(range(2, 100, 2))

[2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98]

## Scenario 2
- Print list of odd numbers

In [203]:
print(list(range(1, 100, 2)))

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99]


In [204]:
list(range(1, 100, 2))

[1,
 3,
 5,
 7,
 9,
 11,
 13,
 15,
 17,
 19,
 21,
 23,
 25,
 27,
 29,
 31,
 33,
 35,
 37,
 39,
 41,
 43,
 45,
 47,
 49,
 51,
 53,
 55,
 57,
 59,
 61,
 63,
 65,
 67,
 69,
 71,
 73,
 75,
 77,
 79,
 81,
 83,
 85,
 87,
 89,
 91,
 93,
 95,
 97,
 99]

## Scenario 3
- Write a program that print out true if 3rd element of the first range is less than 2, print out false if the 5th element of the first range is 5, print out none other wise. 
`x = [list(range(5)), list(range(5,9)), list(range(1,10,3))]`

In [208]:
x = [list(range(5)), list(range(5,9)), list(range(1,10,3))]
if x[0][2] < 2:
    print(True)
elif x[0][4] == 5:
    print(False)
else:
    print(None)

None


## Scenario 4
-  Write a program that print out true if last element of the first range is greater than 3, print out false, if the last element of the second rangee is less than 9 and printout none otherwise. 
`x = [list(range(5)), list(range(5,9)), list(range(1,10,3))]`

In [211]:
x = [list(range(5)), list(range(5,9)), 
     list(range(1,10,3))]
if x[0][-1] > 3:
    print(True)
elif x[1][-1] < 9:
    print(False)
else: 
    print(None)

True


# Exercise

## Accept an integer from the user and display whether it is even or odd 

In [213]:
number = int(input())
if number % 2 == 0:
    print('Even')
else:
    print('Odd')

47
Odd


## In a company an employee is paid as under: If his basic salary is less than Rs. 1500, then HRA = 10% of basic salary and DA = 90% of basic salary. If his salary is either equal to or above Rs. 1500, then HRA = Rs. 500 and DA = 98% of basic salary. If the employee's salary is input through the keyboard write a program to find his gross salary. 

In [216]:
salary = float(input())
if salary < 1500:
    hra = 0.1 * salary
    da = 0.9 * salary
    gross = hra + da + salary
else:
    hra = 500
    da = .98 * salary
    gross = hra + da + salary
print(gross)

123
246.0


## Find the largest among the three numbers eg: 47, 56, 34. 

In [217]:
a, b, c = 47, 56, 34
if a > c and a > b:
    print('a is the largest', a)
elif b > c and b > a:
    print('b is the largest', b)
else:
    print('c is the largest', c)

b is the largest 56


In [218]:
a = 47
b = 56
c = 34
if a > b:
    print(a)
elif b > c:
    print(b)
else:
    print(c)

56


## Write a program that prints out True! if the last 3 char of the string are all digits and print out false! otherwise. Hint: use appropriate method ro check if the requested string slice contain digits only 
`x = "The days of Python 2 are almost over. Python 3 is the king now."` 

In [224]:
x = "The days of Python 2 are almost over. Python 3 is the king now."
if x[-4: -1].isdigit():
    print(True)
else:
    print(False)

False


# Looping Statement
- Loops are used in programming to repeate a specific block of code.
1. for loop
    syntax:
    
    `for <var_name/list_name> in <list_name/str_name/range()>:
        statement1
        statement2
     remaing stat/code`

In [225]:
for i in range(1, 6):
    print(i)
print('Bahar kyun aaya, wapas ander jj')

1
2
3
4
5
Bahar kyun aaya, wapas ander jj


- Range cannot take floating numbers.

In [226]:
numbers = [1, 2, 3, 4, 5, 6]
add = 0
for i in numbers:
    add = add + i
print(add)

21


### 1. Program to print all the genre with expected output as "The genre is : Pop

`genre = ['pop', 'rock, 'jazz']`

In [228]:
genre = ['pop', 'rock', 'jazz']
for i in genre:
    print('The genre is:',i)

The genre is: pop
The genre is: rock
The genre is: jazz


### 2. Program to print all the genre with expected output as 
`"The genre is : po"`

In [230]:
genre = ['pop', 'rock', 'jazz']
for i in genre:
    print('The genre is:',i[0:2])

The genre is: po
The genre is: ro
The genre is: ja


### 3. Write a program using for loop that iterates over x list and prints out remainder of each elements divided by 3

`x = [10, 12, 13, 14, 17, 19, 21, 22, 25]`

In [231]:
x = [10, 12, 13, 14, 17, 19, 21, 22, 25]
for ele in x:
    print(ele % 3)

1
0
1
2
2
1
0
1
1


# While Loop

- Iterates over the block of code as long as condition is true.
- Used when we don't know the number of time to loop/repeat/iterate over the block of syntax:

    `while condition:
        statement1
        statement2
     remaing statement`
- Beware of infinite looping.

In [232]:
count = 0
while count < 3:
    count = count + 1
    print(count)
print('The total is:', count)

1
2
3
The total is: 3


# Using loop print all the index of the x list. 

`x = [10, 12, 13, 14, 17, 19, 21, 22, 25]`

In [233]:
x = [10, 12, 13, 14, 17, 19, 21, 22, 25]
for ele in x:
    print(x.index(ele))

0
1
2
3
4
5
6
7
8


# Q. Write a program to print the factorial of a number accepted from user.

In [235]:
number = int(input())
factorial = 1
while number > 0:
    factorial = factorial * number
    number = number - 1
print(factorial)

23
25852016738884976640000


In [237]:
#for i in range(0, 5):
 #   print('*' * i)
  #  print('', end="")

i = 1
while i <= 4:
    print('*' * i)
    i = i + 1

*
**
***
****


# List Comprehension

syntax:

`[output for i <list_name> if condition]`
- The output of the list comprehension is always a list.

In [238]:
[i**2 for i in [1,2,3]]

[1, 4, 9]

In [239]:
l = [1, 2, 3]
for i in l:
    print(i**2)

1
4
9


# Program to print square of list l only if itme in list are greater than 2.

In [240]:
[x**2 for x in [1, 2, 3] if x > 2]

[9]

## By using list comprehension, please write a program to print the list after removing the value 24 in [12,24,35,24,88,120,155] 

In [241]:
x = [12,24,35,24,88,120,155]
[ele for ele in x if ele != 24]

[12, 35, 88, 120, 155]

## Dictionary Comphrension
- syntax:
    `{output for i in <iterables> if condition}`
- The output of the dictionary comprehnsion is always a dictionary.

In [242]:
{x:x*x for x in range(1, 10)}

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81}

In [244]:
sq = {x: [x*x, x**3] for x in range(0, 20) if x%2==0}
sq

{0: [0, 0],
 2: [4, 8],
 4: [16, 64],
 6: [36, 216],
 8: [64, 512],
 10: [100, 1000],
 12: [144, 1728],
 14: [196, 2744],
 16: [256, 4096],
 18: [324, 5832]}

# Function

- Is a group of realted code/statements that performs a specific tasks.
- Basically takes data in process it and gives back the output/results.
- Function basically breaks large compples data into samller chunks and makes easy to read.
- Avoids repetation of code and helps in resuablilty.
- syntax:
    
    
    `def func_name(parameters):
        "comments wrt functions"
        statements

In [246]:
def kick_24():
    for i in l:
        if i!=24:
            print(i, end = ' ')
l = [12,24,35,24,88,120,155]
kick_24()

12 35 88 120 155 

# Enumerate

- Often, when dealing with iterators, we also get a need to keep a count of iterations. Python eases the programmers’ task by providing a built-in function enumerate() for this task. 
- Enumerate() method adds a counter to an iterable and returns it in a form of enumerating object. This enumerated object can then be used directly for loops or converted into a list of tuples using the list() method.

In [252]:
list(enumerate(range(1, 10)))

[(0, 1), (1, 2), (2, 3), (3, 4), (4, 5), (5, 6), (6, 7), (7, 8), (8, 9)]

## By using list comprehension, please write a program to print the list after removing the 0th,4th,5th numbers in `[12,24,35,70,88,120,155]` 
`Hint : use enumerate.` 

In [253]:
li = [12, 24, 35, 70, 88, 120, 155]
[x for (i,x) in enumerate(li) if i != 0 and i != 4 and i != 5]

[24, 35, 70, 155]

In [254]:
li = [12, 24, 35, 70, 88, 120, 155]
[x for (i,x) in enumerate(li) if i not in (0, 4, 5)]

[24, 35, 70, 155]

# Lambda Functions:

- It is any anonymous function that is defined without function name.
- Uses a keyword "lambda".

- syntax:

        `<variable_name>= lambda <argument1, argument2, ...>`

In [255]:
# lambda arg : expression
sqr_num = lambda a:a**2
print(sqr_num(4))

16


In [256]:
def multi(x, y):
    return x*y
print(multi(1, 2))

2


In [257]:
m = lambda x, y: x*y
print(m(2,3))

6


# filter()

- It filters the sequence(list, tuple,...) with the help of a function which test each of the elements in the sequence is present or not.

In [260]:
# Filter
# syntax: filter(function, sequence/list/tuple..)
letters = ['a', 'b', 'c', 'd' ]

def function_0(variable):
    if variable in letters:
        return True
    else:
        return False

check_seq = ['a', 'c', 'v', 'z', 'x']
filtered = filter(function_0, check_seq)

for i in filtered:
    print(i)

a
c


In [261]:
# Scenario : Want a filtered list which gives me even numbers
seq = [0, 1, 2, 3, 4, 5, 6]
result = lambda x: x % 2 == 0

filter_seq = filter(result, seq)

for i in filter_seq:
    print(i)

0
2
4
6


In [262]:
seq = [0, 1, 2, 3, 4, 5, 6]
result = lambda x: x % 2 != 0

filter_seq = filter(result, seq)

print(list(filter_seq))

[1, 3, 5]


# map()

- Syntax:
    `map(function_name, iterator/seq)`
- Returns an iterator as result after using a function to each of the elementin a given iterator.

In [263]:
# Scenario: Double of the numbers from tuple using lambda
l = (1, 2, 3, 4)
lam = lambda x : x + x
filt = map(lam, l)
print(list(filt))

[2, 4, 6, 8]


In [264]:
# Add both thr list
l1 = [1, 2, 3, 4]
l2 = (1, 2, 3, 4)
result = map(lambda x, y: x+y, l1, l2)
print(list(result))

[2, 4, 6, 8]


# reduce()

- A function that implements a mathematical technique called folding or reduction.
- reduce() is useful when you need to apply fucntion to an iterable and reduce it to a single cumulative value.

- `from functools import reduce `

In [267]:
from functools import reduce

In [265]:
list1 = [1, 2, 3, 4, 5]

def add1(a, b):
    return a + b
print(add1(1, 3))

4


In [268]:
list1 = [1, 2, 3, 4, 5]
reduce(add1, list1)

15

In [269]:
reduce(lambda a,b: a+b, list1)

15

# Modules
- Modules are files that basically contains functions, classes, variables.
    - This makes group related codes into a single file
    - Make a module file in same directory or anyone given directory.
    - Code the neccesary defined statements, and save it in `file_name.py` format.
    - Import that module by saved name.

In [272]:
# Using import statement
# import <module_name>
import module1

In [273]:
# Accessing a module using a dot(.) operator
a = 1
b = 2
module1.addi(a, b)

3

In [274]:
# syntax: from <module_name> import <function_name/class_name/...>
from module1 import addi, subi
print(addi(123, 454))
print(subi(123, 454))

577
-331


In [275]:
from module1 import *
print(divi(324,435))
print(addi(324,435))
print(subi(324,435))

0.7448275862068966
759
-111


# Files and its Operations

## Diferent operations
1. Opening file
2. Writing file
3. Updating file

### Process of performing these operations over file
1. Open a file
2. Perform operations like write/update
3. Always remember to cole that file which was opened.

# Why we need to close file compulsory?
- RAM purpose

In [278]:
# Open file and read that file and store it in variable
f = open("tweets.txt", "r")
# open("<./PDS/file_name>",mode=r,w,a)
f.read()
f.close()

In [279]:
# Open hello.txt and add "Banglore" to it.
f1 = open("hello.txt",'w')
f1.write("Bangalore")
f1.close()
# The problem over here is, it is overwriting the entire file.

In [280]:
# Solution to the above problem.
f1 = open("hello.txt",'a') # We 'a' to append the existing file.
f1.write("Hello World")
f1.close()

# Class

Syntax:
    
class <class_name>:
    attr1,
    attr2,...
    
    methods1():
        ...
    methods2():
        ...

In [281]:
class employee:
    pass

# creating object
amit = employee()

In [283]:
class employee:
    salary = 100
    age = 22
    
    def __init__(self, name):
        self.name = name
        
    def employee_dis(self):
        return 'Employee Name: ',self.name

R_D_employee = employee("amit")
R_D_employee.employee_dis()

('Employee Name: ', 'amit')

In [284]:
class Parrot:
    legs = 2
    eyes = 2
    
    def __init__(self,name,age):
        self.name = name
        # blue_parrot.name = 'blue1'
        self.age = age
        # blue.parrot.age = 5
        
    def sing(self, sound):
        self.sound = sound
        return "It makes sound:",self.sound
    
blue_parrot = Parrot('blu1',5)
print(blue_parrot.sing("Happy"))

green_parrot = Parrot('green1',6)
green_parrot.sing('Sad')

('It makes sound:', 'Happy')


('It makes sound:', 'Sad')

# Exceptions in python

## What is exception?
- Exception is an event that occurs during an execution/running a code/program this basically disrupt the flow of the execution/running of code. 

## Standard exceptions in  python:

1. FileNotFound
2. ImportError
3. RuntimeError
4. NameError
5. TypeError

## Why use exception?
- Not to allow errors and run remaining part of the program.
- Helps in debugging(handle errors in the program and correct them)
- Gives a cleaner code
## What are errors and types?
- Action that cause/gives incoorect result.
Ex: syntax error
> How to handle these errors?

#### try and except block 

In [285]:
a = 10
b = 0
c = a/b 
print(c)
# We have this error

ZeroDivisionError: division by zero

In [286]:
try:
    a = 10
    b = 0
    c = a/b
    print(c)
except:
    print("Cannot divide any int number with a zero, Please enter positive value")

Cannot divide any int number with a zero, Please enter positive value


In [287]:
try:
    a  = 10
    b  = 0

    c = a/b
    print(c)
except ValueError:
    print('Please enter integer number, not a string')
except ZeroDivisionError:
    print('Cannot divide any int a numer with zero, Please enter a positive integer')

Cannot divide any int a numer with zero, Please enter a positive integer


In [288]:
try:
    a  = 10
    b  = 0
    c = a/b
    print(c)
except (ValueError,ZeroDivisionError):
    print('Please enter integer number, not a string, and do please enter a positive integer')

Please enter integer number, not a string, and do please enter a positive integer


In [290]:
try:
    a  = int(input())
    b  = int(input())
    c = a/b
    print(c)
except (ValueError,ZeroDivisionError):
    print('Please enter integer number, not a string, and do please enter a positive integer')
else:
    print('Code Ran Successfully')

10
10
1.0
Code Ran Successfully


# NumPy

## Numpy Array Creation

In [14]:
import numpy as np

In [2]:
# Creating a numpy array
arr1 = np.array([11, 22, 33, 44, 55, 66])
print(arr1)

[11 22 33 44 55 66]


In [5]:
# Syntax: <name of array> = np.arrange(start, stop)

arr2 = np.arange(10) # np.arange- a:array & range
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr3 = np.arange(20, 50)
arr3

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [7]:
arr4 = np.arange(5, 50, 5)
arr4

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [8]:
## Creating a numpy array with linear evenly spaced elements between the start and the end 
## Syntax: np.linspace(<start>, <stop>, <number of elements>)
## Note: Only in this case of numpy array creation the stop will be included

arr5 = np.linspace(0, 2, 4)
arr5

array([0.        , 0.66666667, 1.33333333, 2.        ])

In [9]:
# Creating a numpy array full of zeros
# Syntax: <name of array> = np.zeros(<num>)

arr7 = np.zeros(4)
arr7

array([0., 0., 0., 0.])

In [10]:
# Creating a numpy array full of ones
# Syntax: <name of array> = np.ones(<num>)

arr8 = np.ones(6)
arr8

array([1., 1., 1., 1., 1., 1.])

In [11]:
## Create a 2D array
## Syntax of  2D: name of the array = np.array([list1, list2, list3,..])
list1 = [1, 2, 3, 4]
list2 = [5, 6, 7, 8]
arr9 = np.array([list1, list2])
arr9

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
# Ones array with 2D
# Syntax: <name of array> = np.ones((<rows>, <columns>))
arr10 = np.ones((2, 3))
arr10

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
# Zeros array with 2D
# Syntax: <name of array> = np.zeros((<rows>, <columns>))
arr10 = np.zeros((3, 4))
arr10

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
arr13 = np.diag((1, 2, 3))
arr13

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [15]:
# There are 2 ways to create a random array, 1. rand & 2. randn
## rand(<num>) produces uniformaly distributed random number with range 0 to <num>
## Syntax for creating a random numbers : <name of array> = np.random.rand(<num>) or np.random.randn(<num>)

arr14 = np.random.rand(5)
arr14

array([0.04784242, 0.33225951, 0.62637337, 0.40584655, 0.76211   ])

In [16]:
# Seed is used to get the same numbers as output across

np.random.seed(200)
arr15 = np.random.rand(8)
arr15

array([0.94763226, 0.22654742, 0.59442014, 0.42830868, 0.76414069,
       0.00286059, 0.35742368, 0.90969489])

In [22]:
## 2. randn function
## randn(<num> produces <num> normally distributed (Gaussian) random numbers)

arr16 = np.random.randn(4)
arr16

array([ 0.21348149,  1.01734895,  1.91171178, -0.52967163])

In [18]:
## full function

arr17 = np.full(5, 7)
arr17

array([7, 7, 7, 7, 7])

In [19]:
arr18 = np.full((2,3), 9)
arr18

array([[9, 9, 9],
       [9, 9, 9]])

## Numpy Datatypes

In [23]:
list1 = [5, 50 , 55, 25, 75]
arr1 = np.array(list1, dtype='float')
arr1

array([ 5., 50., 55., 25., 75.])

In [24]:
# One more way to define the dtype in array function

arr2 = np.array(list1, dtype = np.float64)
arr2

array([ 5., 50., 55., 25., 75.])

In [25]:
# One more way to define the dtype in array function

arr3 = np.array(list1, dtype = np.int32)
arr3

array([ 5, 50, 55, 25, 75], dtype=int32)

In [15]:
## Lower data types are converted to higher types. In numeric data ty

arr4 = np.array([10, 15, 45, 75])
arr4

array([10, 15, 45, 75])

In [27]:
type(arr4)

numpy.ndarray

In [16]:
## Checking the data type of elements of the array
## syntax: <name of the array>.dtype

arr4.dtype

dtype('int64')

In [29]:
## In case strings, dtype is the length of the lowest string in the array

arr5 = np.array(['Hello', 'Hi', 'python', 'programming'])
arr5

array(['Hello', 'Hi', 'python', 'programming'], dtype='<U11')

In [30]:
arr5.dtype

dtype('<U11')

In [31]:
arr6 = np.array([False, True])
arr6

array([False,  True])

In [32]:
arr6.dtype

dtype('bool')

In [34]:
# Type casting

arr7 = np.array([3, 4, -10, 5, -20])
arr7

array([  3,   4, -10,   5, -20])

In [35]:
## Syntax for type casting: <name of array>.astype(<dtype>)

arr7.astype(float)

array([  3.,   4., -10.,   5., -20.])

In [36]:
arr8 = np.array([[10, 20, 30], [40, 50, 500], [70, 80 ,90]])
arr8

array([[ 10,  20,  30],
       [ 40,  50, 500],
       [ 70,  80,  90]])

## Numpy indexing & slicing

- Syntax for slicing: 
    `<name of array>` `[<start>: <stop>: <step>]`


In [47]:
arr1 = np.arange(8, 24)
arr1

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [48]:
## Syntax for indexing: <name of array>[<index_value>]
## <index_value> can be positive or negative

arr1[0]

8

In [49]:
arr1[-3]

21

In [50]:
## Slicing with 1D array
## Syntax:<namr of array>[<start>:<stop>:<step>]

arr1[2:6]  # prints all the elements from start i.e. index location 2 to index location 5, the element at index location 6 is exculded

array([10, 11, 12, 13])

In [51]:
arr1[-12:-5]

array([12, 13, 14, 15, 16, 17, 18])

In [52]:
# To move from right to left we give step as negative value
arr1[-5:-12:-1] 

array([19, 18, 17, 16, 15, 14, 13])

In [38]:
arr8

array([[ 10,  20,  30],
       [ 40,  50, 500],
       [ 70,  80,  90]])

In [39]:
arr8[1: , 1:]

array([[ 50, 500],
       [ 80,  90]])

In [41]:
arr8[0:2, 1:]

array([[ 20,  30],
       [ 50, 500]])

- Syntax of 2D array slicing: 
    
    `<name of array>``[start:stop, start:stop]`
- Stop is always exclusive

In [42]:
arr8[0:2,1:]

array([[ 20,  30],
       [ 50, 500]])

In [43]:
## 2D dimensional arrays are indexed using the tuples of integers

arr3 = np.array([[10, 20, 30], [40, 50, 500], [70, 80, 90], [150, 175, 125], [500, 600, 750]])
arr3

array([[ 10,  20,  30],
       [ 40,  50, 500],
       [ 70,  80,  90],
       [150, 175, 125],
       [500, 600, 750]])

In [44]:
arr3[2:4,1:]

array([[ 80,  90],
       [175, 125]])

In [45]:
arr3[:,-1]

array([ 30, 500,  90, 125, 750])

In [46]:
arr3[:,-2]

array([ 20,  50,  80, 175, 600])

## Statistical Operations & Logical Operators

In [56]:
np.random.seed(100)
arr = np.random.randint(5, 50, size = 15)
arr

array([13, 29,  8, 44, 28, 20, 15, 35, 39,  7, 39, 19, 39, 29, 20])

In [57]:
arr.mean()

25.6

In [59]:
np.median(arr)

28.0

In [61]:
np.std(arr)

11.626406724922939

In [62]:
np.sum(arr)

384

In [63]:
np.random.seed(15)
arr2 = np.random.randint(0, 9, size = (3,3))
arr2

array([[8, 5, 5],
       [7, 0, 7],
       [5, 6, 1]])

In [64]:
arr2.mean()

4.888888888888889

In [66]:
np.median(arr2)

5.0

In [67]:
# cumsum is cumulative sum.
arr2.cumsum()

array([ 8, 13, 18, 25, 25, 32, 37, 43, 44])

In [68]:
## row wise cumulative sum axis = 1
arr2.cumsum(axis = 1)

array([[ 8, 13, 18],
       [ 7,  7, 14],
       [ 5, 11, 12]])

In [69]:
## cols wise cumulative sum axis = 0
arr2.cumsum(axis = 0)

array([[ 8,  5,  5],
       [15,  5, 12],
       [20, 11, 13]])

In [70]:
np.median(arr2, axis = 1)

array([5., 7., 5.])

In [71]:
np.mean(arr2, axis = 1)

array([6.        , 4.66666667, 4.        ])

In [72]:
np.cumprod(arr2)

array([   8,   40,  200, 1400,    0,    0,    0,    0,    0])

In [73]:
## var stands for variance
np.var(arr)

135.17333333333332

In [74]:
np.var(arr2, axis = 0)

array([1.55555556, 6.88888889, 6.22222222])

In [75]:
# std stands for standard deviation
np.std(arr)

11.626406724922939

In [76]:
np.random.seed(125)
arr1 = np.random.randint(11, 20, 5)
arr1

array([13, 18, 14, 17, 11])

In [77]:
## Check here, is any of the element is divisible by 7
np.any((arr1 % 7) == 0)

True

In [78]:
np.any(arr1 > 15)

True

In [79]:
np.all(arr1 < 20)

True

In [80]:
arr1[np.any(arr1 > 15)]

array([[13, 18, 14, 17, 11]])

## Basic Operations

In [81]:
np.random.seed(45)
arr1 = np.random.randint(50, 100, 12)
arr1

array([61, 80, 53, 82, 81, 71, 85, 54, 65, 51, 64, 58])

In [82]:
## Calculating the len of the array
len(arr1)

12

In [83]:
## Find the index location of the largest number in the array

arr1.argmax()

6

In [84]:
## Find the index location of the smallest number in the array

arr1.argmin()

9

In [85]:
mat = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
mat

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [86]:
type(mat)

numpy.matrix

In [87]:
mat2 = np.matrix(np.random.randint(25, 75, size = (3, 4)))
mat2

matrix([[48, 71, 33, 37],
        [59, 49, 37, 42],
        [63, 29, 71, 55]])

## Array Shape Manipulation
- Returns an array containing the same data with a new shape.

In [88]:
arr3 = np.arange(12)
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [89]:
# Syntax: <name of array> = <name of array>.reshape(<rows>, <cols>)

arr3 = arr3.reshape(3, 4)
arr3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [97]:
arr4 = np.arange(9)
arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [98]:
arr4 = arr4.reshape(3, 3)
arr4

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [93]:
## Flatten is used to convert Multi dimensional array tp 1D array.
## syntax: <name of array> = <array name>.flatten()

arr4 = arr4.flatten()
arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

## Array Sorting

In [99]:
## Sorting for a 2D array
arr3 = np.array([[4, 5, 2], [3, 1, 9]])
arr3

array([[4, 5, 2],
       [3, 1, 9]])

In [100]:
## Note: In numpy axis - 0 specifies cols and axis - 1 specifies rows
arr3.sort(axis=1)
arr3

array([[2, 4, 5],
       [1, 3, 9]])

In [101]:
arr3.sort(axis=0)
arr3

array([[1, 3, 5],
       [2, 4, 9]])

In [102]:
arr3.T

array([[1, 2],
       [3, 4],
       [5, 9]])

## Copy & Views
- The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of original array.
- The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.
- The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view. 

In [103]:
## Shallow copy

arr2 = arr1.copy()
arr2

array([61, 80, 53, 82, 81, 71, 85, 54, 65, 51, 64, 58])

In [104]:
arr1

array([61, 80, 53, 82, 81, 71, 85, 54, 65, 51, 64, 58])

# Pandas
- Pandas is one of the ost important libraries for python data analysis.

- Pandas has a data structures for easy data analysis. The most used of these data structures are Series and Dataframe. Series data structure is one dimensional, that is, it consists only one column. DataFrame is a 2D data structures. It consists of rows and columns. 

## Series

In [105]:
import pandas as pd

In [106]:
lis = [1, "John", 3.5, "Hello"]
ser = pd.Series(lis)
ser

0        1
1     John
2      3.5
3    Hello
dtype: object

In [107]:
lis_1 = [1, 2, 3, 4]
ser_1 = pd.Series(lis_1) #dtype = int64
ser_1

0    1
1    2
2    3
3    4
dtype: int64

In [108]:
lis_2 = [1., 2.5, 3, 4]
ser_2 = pd.Series(lis_2) # dtype = float64
ser_2

0    1.0
1    2.5
2    3.0
3    4.0
dtype: float64

In [109]:
lis_3 = [1, 2, 3, 'HI']
ser_3 = pd.Series(lis_3) # dtype = object
ser_3

0     1
1     2
2     3
3    HI
dtype: object

In [110]:
## If you want to look at only the values of the series
## Syntax : <name of the series>.values
ser.values

array([1, 'John', 3.5, 'Hello'], dtype=object)

In [111]:
lis_4 = [1, "John", 3.5, "Hello"]
ind = ['a', 'b', 'c','d']
ser_4 = pd.Series(lis_4, index = ind)
ser_4

a        1
b     John
c      3.5
d    Hello
dtype: object

In [112]:
ser_4.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [114]:
ser_5 = pd.Series(np.array(range(2, 20, 5)))
ser_5

0     2
1     7
2    12
3    17
dtype: int64

In [115]:
dic = {'Arun': 56, 'Anil': 85, 'Sunil': 98, 'Gaffoor': 77}
dic

{'Arun': 56, 'Anil': 85, 'Sunil': 98, 'Gaffoor': 77}

In [116]:
ser_6 = pd.Series(dic)
ser_6

Arun       56
Anil       85
Sunil      98
Gaffoor    77
dtype: int64

## Operations in Series
- Indexing & Slicing
- Elementwise & Broadcasting
- Series Data Structures

In [117]:
ser[2]

3.5

In [119]:
## In series the default indexing will always be applicable.
ser_1[2]

3

In [118]:
## While performing slicing default indexing is chosen over the explicitly mentioned indices

ser_2[2:4]

2    3.0
3    4.0
dtype: float64

In [120]:
ser1 = pd.Series([10, 20, 30 ,40])
ser2 = pd.Series([50, 60, 70 ,80])
ser1

0    10
1    20
2    30
3    40
dtype: int64

In [121]:
ser1 + ser2

0     60
1     80
2    100
3    120
dtype: int64

In [122]:
## Broadcasting operation, one number multiplied to each number of series.

ser1 * 3

0     30
1     60
2     90
3    120
dtype: int64

In [123]:
ser2 / 4

0    12.5
1    15.0
2    17.5
3    20.0
dtype: float64

In [124]:
ser = pd.Series([50, 25, 38, 72, 91, 125, 720, 982, 1200])
ser

0      50
1      25
2      38
3      72
4      91
5     125
6     720
7     982
8    1200
dtype: int64

In [125]:
ser.head()

0    50
1    25
2    38
3    72
4    91
dtype: int64

In [126]:
ser.tail()

4      91
5     125
6     720
7     982
8    1200
dtype: int64

In [127]:
ser.describe()

count       9.000000
mean      367.000000
std       466.929063
min        25.000000
25%        50.000000
50%        91.000000
75%       720.000000
max      1200.000000
dtype: float64

In [128]:
ser.value_counts()

50      1
25      1
38      1
72      1
91      1
125     1
720     1
982     1
1200    1
dtype: int64

In [130]:
ser.unique()

array([  50,   25,   38,   72,   91,  125,  720,  982, 1200])

In [129]:
ser.nunique()

9

## DataFrames

In [131]:
dic = {'Name': ['Anil', 'Sunil', 'Gaffoor', 'John', 'Raheem', 'Smith'],
      'Age' : [22, 25, 36, 41, 48, 45],
      'Education' : ['Bachelor', 'Master', 'High School', 'Bachelor', 'Master', 'Bachelor'],
      'Income' : [30, 35, 54, 75, 98, 85]}
dic

{'Name': ['Anil', 'Sunil', 'Gaffoor', 'John', 'Raheem', 'Smith'],
 'Age': [22, 25, 36, 41, 48, 45],
 'Education': ['Bachelor',
  'Master',
  'High School',
  'Bachelor',
  'Master',
  'Bachelor'],
 'Income': [30, 35, 54, 75, 98, 85]}

In [132]:
df = pd.DataFrame(dic)
df

Name  Age    Education  Income
0     Anil   22     Bachelor      30
1    Sunil   25       Master      35
2  Gaffoor   36  High School      54
3     John   41     Bachelor      75
4   Raheem   48       Master      98
5    Smith   45     Bachelor      85

In [133]:
## Getting the names of the columns from the dataframe
## syntax : <name of the dataframe>.columns

df.columns

Index(['Name', 'Age', 'Education', 'Income'], dtype='object')

In [134]:
## Specifying extra column names in the column parameter will create new column with NaN values

df = pd.DataFrame(dic, columns= ['Name', 'Age','Education', 'Income', 'Sex', 'CreditScore'])
df

Name  Age    Education  Income  Sex CreditScore
0     Anil   22     Bachelor      30  NaN         NaN
1    Sunil   25       Master      35  NaN         NaN
2  Gaffoor   36  High School      54  NaN         NaN
3     John   41     Bachelor      75  NaN         NaN
4   Raheem   48       Master      98  NaN         NaN
5    Smith   45     Bachelor      85  NaN         NaN

In [135]:
df.values

array([['Anil', 22, 'Bachelor', 30, nan, nan],
       ['Sunil', 25, 'Master', 35, nan, nan],
       ['Gaffoor', 36, 'High School', 54, nan, nan],
       ['John', 41, 'Bachelor', 75, nan, nan],
       ['Raheem', 48, 'Master', 98, nan, nan],
       ['Smith', 45, 'Bachelor', 85, nan, nan]], dtype=object)

In [136]:
## Getting one single column

df['Age']

0    22
1    25
2    36
3    41
4    48
5    45
Name: Age, dtype: int64

In [138]:
## Getting one single row from the dataframe

df.loc[0]

Name               Anil
Age                  22
Education      Bachelor
Income               30
Sex                 NaN
CreditScore         NaN
Name: 0, dtype: object

In [139]:
df['Sex'] = ['M', 'M', 'M', 'M', 'M', 'M']
df

Name  Age    Education  Income Sex CreditScore
0     Anil   22     Bachelor      30   M         NaN
1    Sunil   25       Master      35   M         NaN
2  Gaffoor   36  High School      54   M         NaN
3     John   41     Bachelor      75   M         NaN
4   Raheem   48       Master      98   M         NaN
5    Smith   45     Bachelor      85   M         NaN

In [140]:
data = pd.DataFrame(
            np.arange(16).reshape(4,4),
            columns = ['London', 'Paris', 'Berlin', 'Istanbul'],
            index = ['one', 'two', 'three', 'four']
)
data

London  Paris  Berlin  Istanbul
one         0      1       2         3
two         4      5       6         7
three       8      9      10        11
four       12     13      14        15

In [141]:
## Selection of the one column from the dataframe

data['Paris']

one       1
two       5
three     9
four     13
Name: Paris, dtype: int64

In [142]:
## Selection of more than one column from the dataframe

data[['Paris', 'Berlin']]

Paris  Berlin
one        1       2
two        5       6
three      9      10
four      13      14

In [143]:
## Selecting(Indexing) one row from the dataframe

data.loc['one']

London      0
Paris       1
Berlin      2
Istanbul    3
Name: one, dtype: int64

In [144]:
## Selecting(Indexing) more than one row from the dataframe

data.loc[['one', 'four']]

London  Paris  Berlin  Istanbul
one        0      1       2         3
four      12     13      14        15

In [145]:
## Conditional indexing(Filtering) from the dataframe

data [ data > 5]

London  Paris  Berlin  Istanbul
one       NaN    NaN     NaN       NaN
two       NaN    NaN     6.0       7.0
three     8.0    9.0    10.0      11.0
four     12.0   13.0    14.0      15.0

### Selecting with loc and iloc

- loc stands for location based indexing
- iloc stands for integer location based indexing

In [146]:
data = pd.DataFrame(
            np.arange(16).reshape(4,4),
            columns = ['London', 'Paris', 'Berlin', 'Istanbul'],
)
data

London  Paris  Berlin  Istanbul
0       0      1       2         3
1       4      5       6         7
2       8      9      10        11
3      12     13      14        15

In [147]:
data.loc[1, 'Berlin']

6

In [148]:
data = pd.DataFrame(
            np.arange(16).reshape(4,4),
            columns = ['London', 'Paris', 'Berlin', 'Istanbul'],
            index = ['one', 'two', 'three', 'four']
)
data

London  Paris  Berlin  Istanbul
one         0      1       2         3
two         4      5       6         7
three       8      9      10        11
four       12     13      14        15

In [149]:
data.loc[['two', 'four'], ['Paris', 'Berlin']]

Paris  Berlin
two       5       6
four     13      14

In [150]:
data.iloc[[1, 3],[1, 2]]

Paris  Berlin
two       5       6
four     13      14

In [151]:
data.loc['two' : 'three','Paris':'Berlin']

Paris  Berlin
two        5       6
three      9      10

In [152]:
data.iloc[1:3, 1:3]

Paris  Berlin
two        5       6
three      9      10

In [153]:
df = pd.DataFrame(
                    np.arange(9).reshape(3,3),
                    index = ['a', 'b', 'c'],
                    columns = ['Paris', 'US', 'UK']
)
df

Paris  US  UK
a      0   1   2
b      3   4   5
c      6   7   8

In [154]:
new_index = ['c', 'b', 'a']
df = df.reindex(new_index)
df

Paris  US  UK
c      6   7   8
b      3   4   5
a      0   1   2

In [155]:
df.reindex(columns = ['UK', 'US', 'Paris'])

UK  US  Paris
c   8   7      6
b   5   4      3
a   2   1      0

In [156]:
## Dropping a column from the dataframe. Specify axis = 1 for dropping columns
df.drop('Paris', axis = 1)

US  UK
c   7   8
b   4   5
a   1   2

In [157]:
## Drop rows of the dataframe

df.drop('a', axis = 0)

Paris  US  UK
c      6   7   8
b      3   4   5

In [158]:
## Alternative to dropping rows without specifying axis parameter 

df.drop(labels = 'a')

Paris  US  UK
c      6   7   8
b      3   4   5

In [159]:
df = pd.DataFrame(
    {'Name' : ['Anil', 'Sunil', 'Vipul', 'Ram', 'John', 'Smith'], 
     'Age' : [22, 25, 36, 41, 48, 45], 
     'Education' : ['Bachelor', 'Master', 'High School', 'Bachelor', 'Master', 'Bachelor'], 
     'Income' : [30, 35, 54, 75, 98, 45]}) 
df 

Name  Age    Education  Income
0   Anil   22     Bachelor      30
1  Sunil   25       Master      35
2  Vipul   36  High School      54
3    Ram   41     Bachelor      75
4   John   48       Master      98
5  Smith   45     Bachelor      45

In [160]:
df.describe()

Age     Income
count   6.000000   6.000000
mean   36.166667  56.166667
std    10.647378  25.949310
min    22.000000  30.000000
25%    27.750000  37.500000
50%    38.500000  49.500000
75%    44.000000  69.750000
max    48.000000  98.000000

In [161]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   Name       6 non-null      object
 1   Age        6 non-null      int64 
 2   Education  6 non-null      object
 3   Income     6 non-null      int64 
dtypes: int64(2), object(2)
memory usage: 320.0+ bytes


In [163]:
df.describe(include = 'O')

Name Education
count      6         6
unique     6         3
top     Anil  Bachelor
freq       1         3

In [164]:
df.describe(include = 'all')

Name        Age Education     Income
count      6   6.000000         6   6.000000
unique     6        NaN         3        NaN
top     Anil        NaN  Bachelor        NaN
freq       1        NaN         3        NaN
mean     NaN  36.166667       NaN  56.166667
std      NaN  10.647378       NaN  25.949310
min      NaN  22.000000       NaN  30.000000
25%      NaN  27.750000       NaN  37.500000
50%      NaN  38.500000       NaN  49.500000
75%      NaN  44.000000       NaN  69.750000
max      NaN  48.000000       NaN  98.000000

In [165]:
## Checking the data type of each specific column of the dataframe 

df.dtypes

Name         object
Age           int64
Education    object
Income        int64
dtype: object

In [166]:
## Shape is used to get the number of rows and number of columns present 

df.shape

(6, 4)

In [167]:
## ndim is used to get the dimension of the dataframe

df.ndim

2

In [168]:
df.columns

Index(['Name', 'Age', 'Education', 'Income'], dtype='object')

In [169]:
df.index

RangeIndex(start=0, stop=6, step=1)

In [170]:
## rename function is used to change the names of columns of the dataframe using axis = 1 as the parameter
## rename function the first paramter has to be always as dictionary
## inplace = True will permanently modify the orginal data frame 
df.rename({'Income': 'Salary'}, axis = 1, inplace = True)

In [171]:
## astype is used to change the type of data

df['Age'] = df['Age'].astype('int')
df

Name  Age    Education  Salary
0   Anil   22     Bachelor      30
1  Sunil   25       Master      35
2  Vipul   36  High School      54
3    Ram   41     Bachelor      75
4   John   48       Master      98
5  Smith   45     Bachelor      45

In [172]:
df.count()

Name         6
Age          6
Education    6
Salary       6
dtype: int64

In [175]:
df.value_counts('Age')

Age
22    1
25    1
36    1
41    1
45    1
48    1
dtype: int64